remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Holy Grail
description: Application for automatic tracking of Holy Grail challenge progress <br/>(for offline characters) in Diablo 2 Resurrected / Diablo 2 LoD / Plugy <br />Free, Open Source, Community drive - for players and streamers.
theme: jekyll-theme-cayman
google_analytics: G-9CFV7QE9V2
