remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Diablo 2 Holy Grail
description: Diablo 2 Holy Grail app, for offline games

show_downloads: true
@import "{{ site.theme }}";
